stages:
  - build
  - test
  - sonarqube-check
  - package
  - deploy
  - release

default:
  image: maven:3.9.9-eclipse-temurin-21-alpine
  tags:
    - avm_groupe7
  before_script:
    - chmod +x settings.sh && ./settings.sh
  retry:
    max: 2
    when:
      - api_failure
      - script_failure
      - unknown_failure

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS_SINGLE_THREAD: "-B -V -ntp -s .settings.xml --fail-at-end"
  MAVEN_CLI_OPTS: "${MAVEN_CLI_OPTS_SINGLE_THREAD} -T 1C"

cache:
  key: "m2-${CI_COMMIT_REF_SLUG}"
  policy: pull-push
  paths:
    - .m2/repository
  when: on_success

check-envvars:
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - >
      if [[ -z "$MAVEN_ENT_PASSWORD" ]]
      || [[ -z "$MAVEN_ENT_USERNAME" ]]
      || [[ -z "$MAVEN_MASTER_PASSWORD" ]]
      || [[ -z "$SONAR_HOST_URL" ]]
      || [[ -z "$SONAR_TOKEN" ]];
      then echo "Missing env vars"; exit 1; fi

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} clean compile

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} -pl '!GUI,!CoverageReport' jacoco:prepare-agent test jacoco:report
  artifacts:
    reports:
      junit: "**/target/surefire-reports/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "**/target/site/jacoco/jacoco.xml"
    paths:
      - "**/target/surefire-reports/TEST-*.xml"
      - "**/target/site/jacoco/jacoco.xml"
      - "**/target/classes/"
    expire_in: 1 week

testIHM:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} -pl 'LexerParser' -am install -DskipTests
    - mvn ${MAVEN_CLI_OPTS} -pl 'GUI' jacoco:prepare-agent test jacoco:report
  artifacts:
    reports:
      junit: "**/target/surefire-reports/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "**/target/site/jacoco/jacoco.xml"
    paths:
      - "**/target/surefire-reports/TEST-*.xml"
      - "**/target/site/jacoco/jacoco.xml"
      - "**/target/classes/"
    expire_in: 1 week

package:
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests package
  artifacts:
    paths:
      - "**/target/*.jar"
    expire_in: 1 week
  needs:
    - test
    - testIHM

sonarqube-check:
  stage: sonarqube-check
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "sonar-cache"
    policy: pull-push
    paths:
      - .sonar/cache
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS_SINGLE_THREAD} -DskipTests sonar:sonar -Dsonar.projectKey=avm-2025-groupe-7 -Dsonar.projectName='avm-2025-groupe-7'
  #  allow_failure: true # Uncomment this line to not fail the pipeline if the SonarQube analysis fails
  needs:
    - build
    - test
    - testIHM

deploy:
  stage: deploy
  retry: 2
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
  needs:
    - package
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests deploy

release:prepare:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: manual
  before_script:
    - chmod +x settings.sh && ./settings.sh
    - apk add git openssh-client
    - git config --global user.email "ci@groupe7.fr"
    - git config --global user.name "CI Release Bot"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "${GITLAB_SSH_PRIVATE_KEY}" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa disc.univ-fcomte.fr >> ~/.ssh/known_hosts
    - git remote set-url origin git@disc.univ-fcomte.fr:projet-amv-2025/groupe-7.git
    - git fetch --all
    - git checkout ${CI_COMMIT_BRANCH}
    - git pull origin ${CI_COMMIT_BRANCH}
  script:
    - mvn ${MAVEN_CLI_OPTS_SINGLE_THREAD} release:clean release:prepare -DpushChanges=true -Darguments="-DskipTests"
  after_script:
    - git push --tags
  artifacts:
    paths:
      - release.properties
      - pom.xml.releaseBackup
    expire_in: 1 day
  allow_failure: false

release:perform:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: manual
  needs:
    - release:prepare
  script:
    - mvn ${MAVEN_CLI_OPTS_SINGLE_THREAD} release:perform -Darguments="-DskipTests"
  allow_failure: false
