stages:
  - build
  - test
  - sonarqube-check
  - package
  - deploy

default:
  image: maven:3.9.9-eclipse-temurin-21-alpine
  tags:
    - avm_groupe7
  before_script:
    - chmod +x settings.sh && ./settings.sh

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -V -ntp -T 1C -s .settings.xml --fail-at-end"

cache:
  key: "m2-${CI_COMMIT_REF_SLUG}"
  policy: pull-push
  paths:
    - .m2/repository
  when: on_success


check-envvars:
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - >
      if [[ -z "$MAVEN_ENT_PASSWORD" ]]
      || [[ -z "$MAVEN_ENT_USERNAME" ]]
      || [[ -z "$MAVEN_MASTER_PASSWORD" ]]
      || [[ -z "$SONAR_HOST_URL" ]]
      || [[ -z "$SONAR_TOKEN" ]];
      then echo "Missing env vars"; exit 1; fi

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} clean compile
  artifacts:
    paths:
      - '**/target/'
    expire_in: 1 week

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  before_script:
    - chmod +x settings.sh && ./settings.sh
    - apk add xvfb libx11-dev xvfb-run
    - export DISPLAY=:0
    - Xvfb $DISPLAY -screen 0 1400x900x24 +extension RANDR &
  script:
    - xvfb-run mvn ${MAVEN_CLI_OPTS} jacoco:prepare-agent test jacoco:report
  artifacts:
    reports:
      junit: '**/target/surefire-reports/TEST-*.xml'
      coverage_report:
        coverage_format: jacoco
        path: '**/target/site/jacoco/jacoco.xml'
    paths:
      - '**/target/'
    expire_in: 1 week

package:
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests package
  artifacts:
    paths:
      - '**/target/*.jar'
    expire_in: 1 week
  needs:
    - test

sonarqube-check:
  stage: sonarqube-check
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "sonar-cache"
    policy: pull-push
    paths:
      - .sonar/cache
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests sonar:sonar -Dsonar.projectKey=avm-2025-groupe-7 -Dsonar.projectName='avm-2025-groupe-7'
  allow_failure: true
  needs:
    - test

deploy:
  stage: deploy
  retry: 2
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'
  needs:
    - package
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests deploy

deploy:manual:
  stage: .pre
  retry: 2
  rules:
    - when: manual
      allow_failure: true
  script:
    - mvn ${MAVEN_CLI_OPTS} -DskipTests package deploy