<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>MiniJAJA</artifactId>
        <groupId>fr.ufrst.m1info.gl.groupe7</groupId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <artifactId>LexerParser</artifactId>
    <version>1.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>LexerParser</name>

    <properties>
        <antlr.outputdirectory>${project.basedir}/src/main/java/fr/ufrst/m1info/gl/groupe7/lexerparser/gen/</antlr.outputdirectory>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>4.13.2</version>
        </dependency>
        <dependency>
            <groupId>fr.ufrst.m1info.gl.groupe7</groupId>
            <artifactId>Memoire</artifactId>
            <version>1.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution> <!-- Cet 'execution' prends le groupId maven du projet et le transforme en chemin ('a.b.c.d' en 'a/b/c/d') -->
                        <id>convert-groupid-to-path</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>groupId.path</name>
                            <value>${project.parent.groupId}</value>
                            <regex>\.</regex>
                            <replacement>/</replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>4.13.2</version>
                <configuration>
                    <visitor>true</visitor>
                    <listener>true</listener>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-minijaja</id>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/antlr4</sourceDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-jajacode</id>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/antlr4/fr/ufrst/m1info/gl/groupe7/lexerparser/gen/jajacode</sourceDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>**/*Test*.class</exclude>
                                <exclude>**/test/**</exclude>
                                <exclude>**/MainCompiler.class</exclude> <!-- Exclude main class used in the development. -->
                                <exclude>**/JajaCodeInterpreter.class</exclude> <!-- Exclude main class used in the development. -->
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
